version: '2'

services:
    brain:
        image: openag/rpi_brain
        expose:
            - 5000
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        command: ~/catkin_ws/devel/env.sh rosrun openag_brain main -D http://db:5984 -A http://brain:5000  --screen -f default -F /home/pi/config/custom_fixture.json
        volumes:
          - /apps/config/:/home/pi/config/
        depends_on:
            - db
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
    db:
        image: dogi/rpi-couchdb
        expose:
            - 5984
        ports:
            - "0.0.0.0:5984:5984"
            - "0.0.0.0:80:5984"
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
